### ISSUE TITLE
`pop_mffimport` vs `pop_readegimff`

### ISSUE THREAD

**Issue by mattansb** [arnodelorme/mffmatlabio#1]
I've been comparing compatibility between the new `pop_mffimport` and the old `pop_readegimff`, and have come across some issues / questions regarding the `EEG.event` struct:

1. What are the units of `EEG.event.duration`? All E-Prime events are of length 1000000. Are these samples? (milli)seconds?
2. Breaks in recording do not appear as events (they did in `pop_readegimff`, as `'break cnt'` events, with `EEG.event.duration` representing the total break in recording). Is there a way to add them?
3. Events are not indexed into `EEG.urevent` (which is blank).

Hope you are able to help, and thanks for this awesome plugin!

Session Info:
* EEGLAB 14.1.2
  * MFFMatlabIO v1.0
  * MFFimport v2.1
* Matlab 2017a
* OS: Win10

**Comment by mattansb** [comment]
Point 2 seems to cause a major problem as it seems that event latencies in `pop_mffimport` do not account for these breaks, thus causing an offset that increases with every break in recording.
See image below:
![offset](https://user-images.githubusercontent.com/35330040/42939085-27877734-8b5d-11e8-882b-0797566398ea.PNG)

**Comment by arnodelorme** [comment]
Can you share a file with a break?

**Comment by mattansb** [comment]
Yes, this one has in the beginning [https://drive.google.com/drive/folders/12SGubGunvusEkl2RcWCRI8AlSygfWnNT](https://drive.google.com/drive/folders/12SGubGunvusEkl2RcWCRI8AlSygfWnNT)

**Comment by arnodelorme** [comment]
Hi Mattan,

The original issue was fixed some time ago.

The new matlabmffio does convert the event to boundaries but not the old plugin keeps them as "break cnt." At least this is what I observed with the file you sent me.

All is good on my side. Let me know if it is not on yours.
Cheers,

Arno
