### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by arnodelorme** [arnodelorme/mffmatlabio#11]
We get the following error in the EEGLAB command line window:

[Fatal Error] :-1:-1: Premature end of file.
MFFRootDoc: error: org.xml.sax.SAXParseException; Premature end of file.
Make sure you call this function with the full MFF ressource path name ******

![unnamed (1)](https://user-images.githubusercontent.com/1872705/66679376-a9564000-ec33-11e9-9ae0-f09c4e416fdb.png)
![unnamed](https://user-images.githubusercontent.com/1872705/66679410-bc691000-ec33-11e9-85c5-8b3209167074.jpg)

**Comment by arnodelorme** [comment]
Followed up with Fiona. We will see if she responds.

**Comment by elannon** [comment]
What was the solution to this problem?
I am getting the same error code

**Comment by Bysmuth** [comment]
Just encountered this problem with two files (using MFFMatlabIO v. 3.6; n.b. this is no longer the current version). In both cases it was due to the existence of an empty (0 bytes) "Events_User_Events.xml" within the .mff container file. Deleting that empty .xml file fixed the problem.

I can provide a sample data file and/or retest with the most current version if it is useful.

**Comment by arnodelorme** [comment]
Yes, please provide a data file for testing purposes. Thank you.

**Comment by Bysmuth** [comment]
I've uploaded a sample data file [here](https://osf.io/wstn9/). You can produce the error by calling pop_mffimport and selecting the unzipped .mff file. On a mac, the error can be resolved by right-clicking on the file in the Finder, clicking Show Package Contents, and deleting Events_User_Events.xml (which is zero bytes), then re-importing.

**Comment by arnodelorme** [comment]
Would you mind posting the data file again?

**Comment by Bysmuth** [comment]
Sure! I just made it accessible again at the same URL I linked to above.

**Comment by arnodelorme** [comment]
Thank you.

**Comment by arnodelorme** [comment]
See folder bugs/mff11

**Comment by arnodelorme** [comment]
Problem fixed. There was an empty event file. Now, these files are detected and skipped.
