### ISSUE TITLE
file with PNS data not importing correctly 

### ISSUE THREAD

**Issue by mamoran66** [arnodelorme/mffmatlabio#16]
case # 15205, Zoran  is using Philips_mff import. and getting the following error window:

mff_import )(line 144) error
Number of PNS raw data channels is not equal to number of PNS channels.
(Error occurred in function mff_import() at line 144)

**Comment by arnodelorme** [comment]
Asked Zoran for a file on Dec 31.

**Comment by arnodelorme** [comment]
Fixed the issue due to a blank channel.
