### ISSUE TITLE
EEGLAB and NetStation 5 Compatibility Issues

### ISSUE THREAD

**Issue by arnodelorme** [arnodelorme/mffmatlabio#19]
From https://github.com/sccn/eeglab/issues/131

**Description**
When processing raw .mff data in EEGLab and then importing it into NetStation 5 for segmentation and baseline correction, NetStation 5 will sometimes crash on seemingly random files, as all of them are being processed the exact same way with the same parameters. Sometimes, it won't crash, but segmentation will spit back an error. Using the NetStation 5 File Validator, we receive a peculiar "error" that seemingly shouldn't cause issues, but it does.

See link below for some images.
https://drive.google.com/drive/folders/1icmLmz04ApN4_4C2_36KepGXkKNE0lc_?usp=sharing

#### Steps to Reproduce These are the processing steps we have been using:
Mark some bad channels on the raw .mff file in NS5
Import EGI/Philips .mff file into EEGLAB. Select "code" and "label" to import as well.
Filter .3 - 30 Hz
Reject continuous data by eye
ASR (without bad channel removal; otherwise default settings)
Rereference
ICA decomposition
ICLabel and remove components
Export .mff file
Import .mff file into NetStation 5 for final processing steps
Segment data**** (where the issue arises, never had issues with the steps preceding or succeeding this part)
Baseline correction
Averaging
Text file export for plotting in R Studio

#### Actual behavior: Two things may happen, which seems to be random: 1. An error in segmenting occurs and we receive the following message: "Info provided: EGISegmentationApplication: error: No segments were created" When putting this file into the file validator, we receive this message: "Problem: Epochs based on signal bin versioning does not match the data in the Epochs.xml file" "Solution: This is for your information only. It should not matter in most cases"
OR

When attempting to segment, Netstation 5 Tools crashes and provides the option to ignore, reopen, or send an error report (which has been done already).
These issues arise only on some of our files, and not others, despite all of them being obtained on the same acquisition system (although this occurs randomly for our new acquisition system as well), and processed the same exact way. Sometimes, we have reprocessed the files again from the beginning, and they will work. There does not seem to be a rhyme or reason except perhaps that it is being mostly processed in EEGLAB and partially in NS5.

OS version	macOS High Sierra 10.13.4
Matlab version	R2018b
EEGLAB version	2019.1

**Comment by rpriefer** [comment]
Hi Arnaud. Sure, I will include a couple of raw files in that google drive. There still seems to be no rhyme or reason - sometimes I will process a file and it will cause these issues; then, I will reprocess it from the very beginning and it will work! Other times, I'll wait a day, simply move the file over again/unzip it and it will work as well! No difference in the file, no different circumstances...perhaps it is just NS5 being finicky!

Thank you!

**Comment by arnodelorme** [comment]
Yes, frustrating. I will have a look.

Arno

**Comment by arnodelorme** [comment]
I believe I have fixed the issue. Please try version 3.1.
