### ISSUE TITLE
Typo in mff_import

### ISSUE THREAD

**Issue by martcous** [arnodelorme/mffmatlabio#2]
The output argument is spelled "events" but is set as "event", therefore output "events" is never set.

https://github.com/arnodelorme/mffmatlabio/blob/0c4ecc7cf8c8b2a481f4c0066415c1fecfa008e9/mff_import.m#L64
https://github.com/arnodelorme/mffmatlabio/blob/0c4ecc7cf8c8b2a481f4c0066415c1fecfa008e9/mff_import.m#L329

**Comment by arnodelorme** [comment]
This has been fixed. Thank you.

**Comment by martcous** [comment]
I think you forgot to push your change :)
