### ISSUE TITLE
Error: Number of PNS raw data channels is not equal to number of PNS channels

### ISSUE THREAD

**Issue by ftadel** [arnodelorme/mffmatlabio#20]
A Brainstorm user reported this issue:
https://neuroimage.usc.edu/forums/t/problems-importing-mff-files/17050

> we have soe problems to import mff-files.
> we record on a 256 channel EGI-system and two additional physio-channels (Physio-box).
> we load the dafyult cap Colin26-EGI-GSN HydroCel256 E001(256), which displays the electroe positions correctly on the brain sourface.
> 
> wehen we then go to "reveiw raw file" there is an error:
> 
> Line 155: mff-import (line 155) Number or PNS raw data channels is not equel to nomber of PNS channels
> Call stack <mff_iport.m at 155
> 
>     in-fopen:mff.m at 59
>     in fopen.m at 115
>     import_raw.m at 126
>     bst_call.m at 28
>     tree_callbacks.m...
> 
> we already tried to delete all the pns channels from the .txt files as if it never was recorded, but this also did not work.
> 
> do you have any idea, what else we can try?

I asked them to post an example file.
Could you comment on this bug? (if possible directly on the Brainstorm forum)

Thanks!

**Comment by arnodelorme** [comment]
Hi Francois,

I think I have fixed that issue recently. I will issue a new release next week and if I do not have negative feedback within a month, I will send you the updated code,

Arno
