### ISSUE TITLE
Error: "Make sure you call this function with the full MFF ressource path name ******"

### ISSUE THREAD

**Issue by AL804** [arnodelorme/mffmatlabio#22]
Dear Arnaud,
Thank you for your work on EEGLab and for maintaining/updating all of the scripts. I'm using Matlab 2019a (with maximum Java Heap settings), have updated Java settings and downloaded the MFFMatlablO2.01 plugin.  Upon importing my .mff file, I get the following error. Please could you advise on what I need to do to fix this?

Thank you,
April

Error using javaObject
No constructor with appropriate signature exists in Java class com.egi.services.mff.api.MFFResourceType

Error in mff_importsignal (line 57)
    signalresourcetype = javaObject('com.egi.services.mff.api.MFFResourceType', javaMethod('valueOf',
    'com.egi.services.mff.api.MFFResourceType$MFFResourceTypes', 'kMFF_RT_Signal'));

Error in mff_import (line 85)
[floatData, allDataSize, srate, nchans] = mff_importsignal(mffFile);

Error in pop_mffimport (line 65)
EEG = mff_import(fileName);

Error in importANDmodifyP50 (line 17)
    EEG = pop_mffimport(sprintf('%s%s', filepath, filename), 'code'); %needs MFFMatlabIO2.01 plugin

Error in pipelineP50 (line 33)
    importANDmodifyP50(dirList{i}, raw_dir)

**Comment by arnodelorme** [comment]
Dear April,

Can you try again with version 3.1 (the latest) and tell me if there is still a problem. If there is still a problem, would you mind to share an MFF file with me. 

Best wishes,

Arno

**Comment by AL804** [comment]
Hi Arno, 
I've tried it with 3.1 and the same exact error message occurs.  In case there are issues related to file size constraints, please find the Dropbox link to the MFF file here (link will expire in 2 weeks):  https://www.dropbox.com/sh/zku12zvv93smf14/AAAR20oDYgEuqGT4P2cllkGoa?dl=0

**Comment by arnodelorme** [comment]
Dear April,

I have tried your file under Windows and Mac and it works for me. I am not sure how to help more. I would try removing all the path from Matlab, do a clean install of EEGLAB and use version 3.3 of the plugin (just released).

Best wishes,

Arno

**Comment by kns37** [comment]
Dear Arno,

I am experiencing the same error mentioned by April on my PC (the plugin works just fine on my Mac). I tried doing a clean install of Matlab 2018a (with updates) and a clean install of EEGLAB 14.1.2b. I tried using versions 2.01, 3.3 and 3.4 but get the same error from the command line and the GUI. 

I'd appreciate any guidance you can provide to resolve this. I am happy to set up a remote session with you and have you try the code on my workstation if it helps identify the cause of this issue since these errors seem to not replicate well. 

Best,
Sahana

**Comment by arnodelorme** [comment]
Dear Sahana,

Let me try on Windows and see if that works for me.
Best wishes,

Arno

**Comment by kns37** [comment]
Hi Arno,

Following up on this. Did you have success using the plugin on a windows 10 platform?
Thank you again for helping me with this.

 Best,
Sahana

**Comment by arnodelorme** [comment]
Hi Sahana,

I have tried on again on Windows and no problem on my side. I am not sure how to help further. The problem might arise because you also have the plugin mffimport and mffmatlabio uses the wrong Java library.

Best,

Arno

**Comment by kns37** [comment]
Success! Thank you, Arno. That was indeed the issue. It seems that having the mffimport plugin interferes with the mffmatlabio plugin only on Windows. They coexist okay on Macs. I appreciate your feedback!

Sahana

**Comment by arnodelorme** [comment]
OK, thank you for letting me know. I will add a piece of code to check if the other plugin is present.
