### ISSUE TITLE
2D, 3D Differences when using default MFF sensor coordinates vs adultaverage64.sfp

### ISSUE THREAD

**Issue by mamoran66** [arnodelorme/mffmatlabio#26]
A user has noticed a difference when viewing sensor positions and interpolated views when using the default 3D coordinates stored in the MFF versus .sfp files imported from our website. The difference could indeed be with the coordinates themselves. I am hoping you can rule out a difference in the way the two methods of using sensor positions are imported or transformed that might explain the difference. If you have a way to directly check the two sets of coordinates, that would also resolve the question. Issue from customer:

"Our main concern is the difference in channel locations between the "AdultAverageNet64_v1.sfp" and the MFFMatlabIO plugin. To demonstrate, I've added two more figures to the email. We ran an ICA twice, using the  "AdultAverageNet64_v1.sfp" as our channel locations and a second time using the MFFMatlabIO plugin channel locations. We've plotted IC1 using both methods. The eye electrodes for the ".sfp" file looks off. Some of the spacing is a bit off as well (looking at the frontal electrodes)."

I've attached the SFP and the resulting view, one default and one sfp
[KU.zip](https://github.com/arnodelorme/mffmatlabio/files/4635897/KU.zip)

**Comment by arnodelorme** [comment]
This is because the 3-D plotting function has automated electrode alignment to the 3-D head mesh for standard EGI coordinate files. This is not the case if you have a custom file. In this case, you need to optimize the alignment between electrode and 3-D mesh yourself.
