### ISSUE TITLE
Can't import more than one file using MFFMatlabIO

### ISSUE THREAD

**Issue by AlanAHartley** [arnodelorme/mffmatlabio#27]
I am able to import a single Netstation MFF file using MFFMatlabIO without difficulty.  But then, when I later attempt to import another file, I get the error message "No class com.egi.services.mff.api.LocalMFFFactoryDelegate can be located on the Java class path.  (Error occurred in function mff_importsignal() at line 46)"

I am guessing this may be related to "When the Java Heap Memory is at its default level, few files can be imported.   There is a special message guiding users how to increase the default settings  in Matlab in case they encounter an error. Importantly, some large files require a computer with 16Gb of RAM or more (or Java Heap of 4Gb)."  But there is no message about increasing space.

Running EEGLAB 2019 under MATLAB e2020a and Win10.  i7 processor with 8Gb.

Any guidance would be greatly appreciated.

**Comment by arnodelorme** [comment]
I think it might be related to the fact that you have the MFFimport plugin installed as well. Would you mind to check.

**Comment by AlanAHartley** [comment]
Thanks for the suggestion.  It doesn't appear that I have MFFImport installed:
EEGLAB: adding "Cleanline" v1.04 (see >> help eegplugin_cleanline)
EEGLAB: adding "ICLabel" v1.2.6 (see >> help eegplugin_iclabel)
EEGLAB: adding "MFFMatlabIO" v3.4 (see >> help eegplugin_mffmatlabio)
WARNING: for plugin "SASICA" version in the folder name "1.3.4" and in the eegplugin_ file ".1.3.7" differ
EEGLAB: adding "SASICA" v1.3.4 (see >> help eegplugin_SASICA)
EEGLAB: adding "clean_rawdata" v2.1 (see >> help eegplugin_clean_rawdata)
EEGLAB: adding "dipfit" v3.3 (see >> help eegplugin_dipfit)
EEGLAB: adding "erplab" to the path; subfolders (if any) might be missing from the path
EEGLAB: adding "firfilt" v2.4 (see >> help eegplugin_firfilt)
________________________________

**Comment by arnodelorme** [comment]
Yes, it could be the Java heap although the error is different.
Did you try increasing the heap. Send me a datafile (through Google Drive or Dropbox if you think it might help).

Arno

**Comment by AlanAHartley** [comment]
No, I didn’t try that.  How do I increase the Java heap?

Alan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by arnodelorme** [comment]
In your Matlab preferences, select “General” then “Java Heap Memory”

**Comment by AlanAHartley** [comment]
Yes, indeed, increasing the Java Heap to 1059 allowed me to import another file without difficulty.

Thanks!
Alan
________________________________

**Comment by arnodelorme** [comment]
Good to hear

**Comment by AlanAHartley** [comment]
Correction.  Increasing the Java heap allowed importing two files but the third one produced the same error.  I could probably increase the heap further but I'm guessing that would just up the limit a bit.  These are 256 channel X 250 Hz X 30 min recordings so size probably matters.

Alan
________________________________

**Comment by arnodelorme** [comment]
Yes, although importing files one after the other should not be a problem because heap memory should be release. Maybe there is a bug in the Java implementation? 

> Correction. Increasing the Java heap allowed importing two files but the third one produced the same error. I could probably increase the heap further but I'm guessing that would just up the limit a bit. These are 256 channel X 250 Hz X 30 min recordings so size probably matters.
> 
> Alan
> ________________________________
> From: Arnaud Delorme <notifications@github.com>
> Sent: Tuesday, May 26, 2020 9:43 AM
> To: arnodelorme/mffmatlabio <mffmatlabio@noreply.github.com>
> Cc: Alan Hartley <ahartley@scrippscollege.edu>; Author <author@noreply.github.com>
> Subject: Re: [arnodelorme/mffmatlabio] Can't import more than one file using MFFMatlabIO (#27)
> 
> 
> Good to hear
>

**Comment by AlanAHartley** [comment]
Yes, that's what I was thinking.
________________________________
