### ISSUE TITLE
error when creating a new mff file

### ISSUE THREAD

**Issue by ometett** [arnodelorme/mffmatlabio#28]
Hi Arno,

I am trying to synchronize my EEG recordings with my MEG recordings so I want to basically scale my EEG times to  match my MEG times. I scale them with polyfit and I have no issue obtaining scaled values. I currently am able to get samples that are the same with my MEG recording but I am having trouble creating the new mff file with my new events. In my unscaled EEG, I had 120 events and I have the same number for scaled EEG so no event is missing. I am having the error " No method 'setY' with matching signature found for class 'com.egi.services.mff.api.Sensor'. Could you help me on how to fix this error? I will attach the screenshot of the error message below.

Regards,
<img width="844" alt="error" src="https://user-images.githubusercontent.com/68041481/88101497-ae9dcf00-cb63-11ea-9cd8-0d131c2a13bd.PNG">

**Comment by arnodelorme** [comment]
The function detected channel locations but they are missing the "Y" coordinate apparently. Maybe because it is MEG?
Best wishes,

Arno

**Comment by ometett** [comment]
But these are still the events I have obtained from EEG. I just scaled the sampling of them with polyfit. I am not using the events from MEG to create an mff file. 

Regards,
Omer

**Comment by arnodelorme** [comment]
The error is about channel location not about events.

Arno

**Comment by ometett** [comment]
Hi Arno,
I realized that I have been getting a warning about my pop_fileio saying unable to import channel location. Is it possible that this is happening because software runs pop_fileio instead of pop_fileio2 ? I attached the ss of the warning message below.

Regards,
<img width="1067" alt="error2" src="https://user-images.githubusercontent.com/68041481/88244688-2cdc9d00-cc5a-11ea-88c8-bef0a8514f72.PNG">

**Comment by arnodelorme** [comment]
Would you mind to share the MFF file you are trying to import and export and I will have a look. The error you are seing could be a problem.

Arno

**Comment by ometett** [comment]
I sent it to your gmail account.

-Omer

**Comment by arnodelorme** [comment]
I have checked the file.
I have imported it, exported it and reimported it. All seems good on my side.
Are you using the most up to date version of the plugin?

Arno

**Comment by ometett** [comment]
Oh, that's interesting! I don't know if I am using the latest version. How can I check the version of the plugin? Also, this is the call I use to recreate the mff file with the scaled events, I will attach below. Could you tell me if that's in the correct format?

Regards,
![Ekran Alıntısı](https://user-images.githubusercontent.com/68041481/88251646-10982a80-cc71-11ea-88d1-5b7120c8136f.PNG)
