### ISSUE TITLE
error exporting epochs

### ISSUE THREAD

**Issue by ometett** [arnodelorme/mffmatlabio#29]
Hi Arno,

I was able to fix the issue with importing channel locations by updating the plugin to the latest version thanks to your guidance.  I now have one type of error when exporting epochs. I am only changing and the sample of the eeg file and keeping everything the same but it gives me an error " Array indices must be positive integers or logical values."

Error in mff_exportepochs (line 63)
        durations = [0 durations durations(end) ];

I thought it could be fixed by setting the duration of each event to 0 but that did not help.  I will attach the screenshot of the error down below. Any of your help is very much appreciated, thank you for your time.

Regards,
![error](https://user-images.githubusercontent.com/68041481/88360425-40136980-cd3b-11ea-8887-83efd32156c8.PNG)

**Comment by arnodelorme** [comment]
Let me try with the data you sent. What do you mean by "changing and the sample of the eeg file.” You mean changing the sampling rate?
I am not sure what Fieldtrip does with your data structures. Could you try doing the same under EEGLAB?

Arno

**Comment by ometett** [comment]
I do a polyfit with meg times and eeg times, get slope and offset values and use them to scale the eeg event samples to match meg event samples. I don't change the sampling rate they both stay at 1000.

**Comment by ometett** [comment]
I also perform ft_preprocessing to get a single continuous trial. Could that be a reason why? Because it seems like boundaryEvent is always empty and the program fails when the line "durations(end)" called.

**Comment by arnodelorme** [comment]
Yes, it could be the reason. I am not sure.

Arno
