### ISSUE TITLE
creating a new mff file

### ISSUE THREAD

**Issue by ometett** [arnodelorme/mffmatlabio#30]
Hi Arno,

I fixed all my errors thanks to your guidance, my code works fine, but I also would like to be able to crop some data out of my EEG(.mff) file. Like for example, I want to delete the portion of the data from second 0 to second 10 but I could not find a built in function or anything like that to do that. I know that for edf files there is edfread function in matlab to help you that but I wonder if there is some way to able to do the same thing with .mff files. If you could help me I would appreciate it! Thanks for the time.

Regards,

**Comment by arnodelorme** [comment]
You may use EEGLAB menu item “Edit > Select data”

Or use the pop_select(EEG, …)

function. You can use fieldtrip2eeglab.m and eeglab2fieldtrip.m to convert the data back and forth from Fieldtrip to EEGLAB.
Cheers,

Arno

**Comment by ometett** [comment]
would pop_select function work with .mff files ?

Regards,

**Comment by arnodelorme** [comment]
Yes, it is an EEGLAB function

**Comment by ometett** [comment]
Arno,
I have been trying to exclude a selection portion of my eeg recording but I am keep getting the error dot indexing is not supported for this type. It seems like it is able to get my EEG file though. I attached my error my message below. If you could help, that would be clutch!

Regards,
<img width="1271" alt="cptr4" src="https://user-images.githubusercontent.com/68041481/88863355-3751e600-d1c8-11ea-89b1-b2e0d2c0a516.PNG">
