### ISSUE TITLE
eeglab2fieldtrip doesn't care header in the struct

### ISSUE THREAD

**Issue by ometett** [arnodelorme/mffmatlabio#31]
Hi Arno,

I converted my file to eeglab and got rid of the portions that I don't want but when I convert it back to fieldtrip with preprocessing option it does not create header inside the struct and because it does not have the events I can not create a new mff file. How can I get the header when I am converting eeglab back to fieldtrip?

Regards,

**Comment by arnodelorme** [comment]
We have fixed the event issue 568a00e . Hopefull this will solve your problem.
