### ISSUE TITLE
PNS Data not imported Properly

### ISSUE THREAD

**Issue by jimark13** [arnodelorme/mffmatlabio#33]
I am trying to import an .mff file from EGI net station that has both EEG and EMG that is collected synchronously. I am able to process the EEG with no issues but when I try importing the EMG data, by running the mff_importpnsset.m script, I am met with "Error in mff_importpnsset (line 43)
pnsURI = fullfile(mffFile, 'pnsSet.xml');"

I am at lost for trying to import the PNS data alone. When using the pluging MFFimportv2.3, the PNS data loads 2 channels instead of 3. Please help

**Comment by arnodelorme** [comment]
Could you share a data file?

**Comment by jimark13** [comment]
Sent over dropbox to your email. Unfortunately, the file is too large for github. Thank you in advance

**Comment by arnodelorme** [comment]
Got the file. The MFF folder is missing signal*.bin files. It cannot be imported without these files. Cheers

**Comment by jimark13** [comment]
Sorry, it seems like not everything was on the dropbox. I have attached a new file that is much smaller and should have 2 channels of EMG rather than 1.  I've uploaded a screenshot of the GUI as well as the raw data collected.


Jasper Mark

Research Assistant  | Cassidy Plasticity Lab

The University of North Carolina at Chapel Hill

School of Medicine – Division of Physical Therapy

Phone: 919-539-1815


________________________________

**Comment by arnodelorme** [comment]
Seems like the new EMG file does not contain the data either, see my email as well

![Uploading Screen Shot 2020-10-06 at 7.26.18 AM.png…]()
