### ISSUE TITLE
MFF export issue with EEG data without events

### ISSUE THREAD

**Issue by synchen232** [arnodelorme/mffmatlabio#35]
Hello, there is a issue when I output mff file by mff_export with EEG data which dose not have events. the mff_export shows error:

```
Dot indexing is not supported for variables of this type.

Error in mff_exportevents (line 78)
    if ~all(cellfun(@(x)isequal(x, 'boundary'), {events(indEvents).type}))

Error in mff_export (line 58)
mff_exportevents(EEG, outputFile);
```

The program in line78 access the variable "events" whatever it will be exist, I think that is be the reason cause the error during output.

**Comment by arnodelorme** [comment]
Thank you. This has been fixed in #568a00e
