### ISSUE TITLE
exporting files with excluded channels scrambles coordinates

### ISSUE THREAD

**Issue by mamoran66** [arnodelorme/mffmatlabio#36]
A user, Anne Arnett has found that if channels are removed in EEGlab, the resulting file imported back into net station has a channel/coordinates mismatch.

I used the IO to export .set files to .mff format this weekend and Gini and I tried to look at them in netstation today. We discovered that during the export, the electrode coordinates are mapped to the channel numbers rather than labels. The problem with this for my data is that we remove rim and eye electrodes early on so we are down to 112 electrodes after processing. The channel numbers shift accordingly (so that they are 1:112) and no longer align with the correct coordinates. However, the channel names/labels (e.g., “E23”) remain consistent, and are correctly mapped to the coordinates in eeglab/matlab.
 
Is there a way to specify the way the electrode coordinates are mapped during the .set->.mff export process so that coordinates are derived from channel names rather than numbers?

**Comment by mamoran66** [comment]
The customer further reported the issue was noticed in the 2D display, which I believe is the sensor layouts, not coordinates

**Comment by arnodelorme** [comment]
Fixed
