### ISSUE TITLE
Class not found in Java classpath com.egi.services.mff.api.LocalMFFFactoryDelegate

### ISSUE THREAD

**Issue by ftadel** [arnodelorme/mffmatlabio#37]
A user of Brainstorm reported this error:
https://neuroimage.usc.edu/forums/t/brainstrom-encountered-an-error-while-importing-data/30625

```
Error in mff_importsignal.m
** Error: Line 50: Wrong use javaObject
** Class not found in Java classpath com.egi.services.mff.api.LocalMFFFactoryDelegate
**
** Call stack:
** >mff_importsignal.m at 50
** >mff_import.m at 85
```

Any suggestion?

**Comment by arnodelorme** [comment]
Hi Francois,

I think this is because this person has another plugin installed with an older version of the JAVA library. See below.

https://github.com/arnodelorme/mffmatlabio/issues/27

Let me know if this is not the case.
