### ISSUE TITLE
Difference between sensorLayout.xml and coordinates.xml

### ISSUE THREAD

**Issue by const7** [arnodelorme/mffmatlabio#42]
Can you tell the difference between these two files? It looks very similar. And also, what do these files correspond to when loading into EEGLab's EEG struct? Thank you.

**Comment by arnodelorme** [comment]
These are MRI files. The plugin is about EEG. Look at this page for more info https://bids-specification.readthedocs.io/en/stable/

**Comment by const7** [comment]
Sorry for the possible misleading.
These two are files under the EGI/Phillips .mff file folder like this:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/19154386/161882480-33bb1d9d-5e77-49f3-a84a-8687e418ea0d.png">

I'm quite confused about them since they both have `x`, `y`, `z` like coordinate fields.
![image](https://user-images.githubusercontent.com/19154386/161883026-8d115bf2-02a2-4890-9e12-7d74ed5a9f5a.png)

It seems that coordinates.xml is imported to `EEG.chanlocs`. But if .mff already has location information what does the standard channel location file (like `GSN128.sfp`, `GSN129.sfp`) in eeglab do?

Thanks again for your time!
