### ISSUE TITLE
Error importing .mff file

### ISSUE THREAD

**Issue by Brain-Mapping** [arnodelorme/mffmatlabio#43]
when I import .mff file in brainstorm using your plugin, I am getting the below error. I tried updating the plugin, but that didn't solve it yet.

![image](https://user-images.githubusercontent.com/17823647/214818486-5e277218-4894-4651-af60-af584e540834.png)

**Comment by arnodelorme** [comment]
The plugin has been updated to fix that problem (but not in brainstorm
yet). Can you share your data file?

**Comment by Brain-Mapping** [comment]
Thank you for the prompt response, here is the file.

Can you please update those fixes in the brainstorm plugin?

[2102114_20190824_112910_fil_seg_bcr_ave.mff.zip](https://github.com/arnodelorme/mffmatlabio/files/10515442/2102114_20190824_112910_fil_seg_bcr_ave.mff.zip)

**Comment by arnodelorme** [comment]
There is an issue with the field relativeBeginTime in your event file Event_user Marker.xml
When I set this field to 0, I can import the file. This is a Java MFF issue, so beyond the plugin to address.

**Comment by Brain-Mapping** [comment]
Yes, we could import now. That was a great help. Last day we also found the same fix. I am about to post you.
