### ISSUE TITLE
Event misalignment when importing mff segmented data

### ISSUE THREAD

**Issue by merilora** [arnodelorme/mffmatlabio#44]
Hi, I am having an issue with importing mff segmented data into EEGlab. The time of the triggers in the mff files is not aligned with the event markers from categories.xml as these events appear to be shifted by several milliseconds. This delay is also not consistent, making it hard for me to understand where the delay comes from. In other words, in the column 'type', the trigger STAT should always overlap with one of 4 conditions (e.g. Plant or Animal) from categories.xml, however the conditions tend to appear several milliseconds after STAT.  I also get these warnings when importing the data: 

eeg_checkset warning: 3rd dimension size of data (115) does not match the number of epochs (1), corrected
eeg_checkset note: upper time limit (xmax) adjusted so (xmax-xmin)*srate+1 = number of frames
eeg_checkset warning: 36/443 events had out-of-bounds latencies and were removed

Many thanks for any help you can offer.

**Comment by arnodelorme** [comment]
Is it possible for you to share a data file?

**Comment by merilora** [comment]
Thanks for the prompt response! Sure, here's a [data file](https://essexuniversity.box.com/s/lpefxliu7hx9thmjri3p5rla65iheee9).

**Comment by merilora** [comment]
The 4 conditions (e.g. Plant or Animal) are added to the file as categories during segmentation (see screenshot of segmentation tool) and they won't show on the segmented file as triggers. I can see the conditions if I view the data as categories though. If it is of any help, I also tried analysing the data with Wtools and I do not see the same shift when opening the file (i.e. the categories align correctly with the STAT triggers). 
<img width="1144" alt="Screen Shot 2023-04-18 at 8 50 36 AM" src="https://user-images.githubusercontent.com/39369609/232712231-121fa150-55f1-496d-bac8-5b57a81e8964.png">

**Comment by merilora** [comment]
Hi, I was wondering if there was any update with regard to this issue and if there's any other information I can provide to help figuring this out?

**Comment by arnodelorme** [comment]
The file is no longer there. Would you mind to upload it again?

**Comment by arnodelorme** [comment]
Might have found the file. See bugs/MFF44 folder

**Comment by arnodelorme** [comment]
This was a complex issue. It has been fixed.
