### ISSUE TITLE
Import Signal issue - Cannot open the signal resource

### ISSUE THREAD

**Issue by IsaacEGI** [arnodelorme/mffmatlabio#45]
Dear Arnaud,

I have a customer reporting an issue importing and MFF file to EEGLAB.

The first thing I saw is that the MFF contents still had the acquiring.xml file (the recording was not stopped properly for some reason). Once I deleted it, it was not being imported to EEGLAB as it was missing the epochs file, and also the event file was reporting the issue: _"XML documents structure must start and end..."_. After checking the XML, the file was missing a closing structure: /eventTrack.

Once I added this structure and created an epoch file using the FileValidator Application of EGI, the mffmatlabio import was reporting a new issue: 
_"Error using mff_importsignal
Error: Can not open the signal resource.\n"_.

What can be causing this issue on the import? Here is a link to the files: https://electricalgeodesics.sharefile.com/d-seea0430f9e184c99842381eafe25dab1

The description of how the recording was done:
"Session takes up to approximately 22 minutes. During the session, the participants are responding with one button on Chronos device.
The triggers are the beginning of a trial, stimulus appearance, response if one was made, and TRSP.
Three built-in stops exist: at the beginning, at the end of Block A, at the end of Block B, and the recording stops at the end of Block C. It is possible, if necessary, to stop recording using the "P" key, and resuming using any key. I do not know if it happened at the questioned mff file, however, I can say it is unlikely."

Please, if you need more information let me know.

Thank you and best wishes,

Isaac Valls Giménez

**Comment by arnodelorme** [comment]
Yes, I will look into it.

**Comment by arnodelorme** [comment]
Apologies it took so long. The event files were corrupted missing some text. It is likely that the hard drive was full and that when the file was copied an saved, only part of the file was saved. It is easy to see that the file was corrupted. Both files are corrupted in the same way. After removing the corrupted file, I could import them and visualize them.

![Screenshot 2024-05-09 at 4 24 11 PM](https://github.com/arnodelorme/mffmatlabio/assets/1872705/f4ef7c11-6027-44e3-be88-42b44b3f8608)

![Screenshot 2024-05-09 at 4 23 16 PM](https://github.com/arnodelorme/mffmatlabio/assets/1872705/c6e5dd21-555a-45dd-a246-c95bc1527d1c)
