### ISSUE TITLE
Importing 10-20 labels

### ISSUE THREAD

**Issue by IsaacEGI** [arnodelorme/mffmatlabio#49]
Dear Arnaud,

I am reporting this issue more as a feature request. We have some customers who use the DIPFIT plugin in EEGLAB. This plugin requires a co-registration of the electrodes positioning to the 10-20 layout, and as our MFF files use the E1, E2, ... labels, this has to be done automatically.

I was trying different ways to get to use that plugin easier and I tried to import the MFF file to EEGLAB after a montage modification using our Net Station Tools software. This tool, besides being used to re-reference also allows to change the layout to the 10-20 for example. I thought that when importing the MFF in EEGLAB after this modification, the labels would be taken as the 10-20 and not the E1 format.

Is there any way that the mffmatlabio plugin could read the 'sensorLayout.xml' sensor names and introduce them to the electrode locations of EEGLAB? This would allow them to use the automatic selection of the Co-Register function in the DIPFIT.

Thank you,

Isaac

**Comment by arnodelorme** [comment]
Hi Isaac,

If the channels are in the MFF format, it is not compatible with the 10-20 system (except for vertex electrode Cz). There is nothing that can be done (it is like trying to convert a bolt in imperial unit to metric unit, there is no perfect match). EEGLAB will automatically align the electrodes to a 10-20 montage when you perform source localization.

Arno

**Comment by IsaacEGI** [comment]
Hi Arnaud,

Thank you for your quick reply and the information shared!

I have not been able to find a way to align them automatically with EEGLAB, how is this done?

While exploring the Co-Register option in DIPFIT, I noticed an EGI option, but in the command window it mentions it is not implemented (please see the screenshot attached). Would this option potentially serve as a way for conducting automatic source localization?

Thank you for your help!

Best wishes,

[Logo  Description automatically generated]
Isaac Valls-Giménez
Product Support Specialist
Email: ***@***.******@***.***>           Phone: +31681420058
Connect to my LinkedIn<https://www.linkedin.com/in/isaac-valls-gim%C3%A9nez-297643234/>

- For on-demand answers to many technical questions, visit www.egi.com/knowledge-center<http://www.egi.com/knowledge-center>
- For technical support: ***@***.******@***.***>
- For sales inquiries: ***@***.******@***.***>
- For order updates: ***@***.******@***.***>



From: Arnaud Delorme ***@***.***>
Date: Friday, November 10, 2023 at 5:31 PM
To: arnodelorme/mffmatlabio ***@***.***>
Cc: Isaac Valls-Giménez ***@***.***>, Author ***@***.***>
Subject: Re: [arnodelorme/mffmatlabio] Importing 10-20 labels (Issue #49)
This email was sent from outside of Welcony. Please do not click links or open attachments unless you recognise the source of this email and know the content is safe.

Hi Isaac,

If the channels are in the MFF format, it is not compatible with the 10-20 system (except for vertex electrode Cz). There is nothing that can be done (it is like trying to convert a bolt in imperial unit to metric unit, there is no perfect match). EEGLAB will automatically align the electrodes to a 10-20 montage when you perform source localization.

Arno

**Comment by arnodelorme** [comment]
Can you share a data file? Also feel free to send me direct emails and CC trey.

**Comment by arnodelorme** [comment]
Closing this report for now.

**Comment by arnodelorme** [comment]
There is no magic as there is no correspondence between EGI locations and 10-20 (except for Cz). It is just a different system. However, when I imported the files Isaac shared, I have noticed that EEGLAB did not automatically find the transformation to align with the 3-D head model (itself aligned with 10-20). I will try to fix that.
